// angular-repo/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppComponent {
  title = 'angular-repo';
}

<main class="main">
  <div class="content">
    <div class="left-side">
      <star-rating rating="3" max="5"></star-rating>
      <weather-component city="chennai"></weather-component>
      <tag-label label="Lit" color="#28a745" textColor="#fff"></tag-label>
      <progress-ring progress="75" radius="40" color="green"></progress-ring>
      <star-rating max="5" rating="3"></star-rating>
      <weather-component city="Jammu"></weather-component>
    </div>
  </div>
</main>
<router-outlet />

// react-repo/src/App.tsx
import "./App.css";
import "my-lit-components";

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <star-rating rating="3" max="5"></star-rating>
        <weather-component city="chennai"></weather-component>
        <progress-ring progress="75" radius="40" color="green"></progress-ring>
      </header>
    </div>
  );
}

export default App;
